version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /opt/mongoData:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  library-link-search-server-container:
    image: com.rhutzel.librarylink/library-link-search-server
    volumes:
      - /data/library-link-search-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
